/**
 * Reserved Slugs
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from the backend API.
 * To regenerate, run: pnpm generate:slugs
 *
 * These slugs are reserved for system pages and cannot be used for categories.
 * This list is fetched from the backend validation in src/Validator/ReservedSlugValidator.php
 *
 * Generated: 2025-12-12T07:43:59.379Z
 * Source: http://127.0.0.1:8081/api/slug/reserved
 *
 * These routes have their own pages in app/[locale]/(public)/ directory:
 * - /all - All articles page
 * - /search - Search page
 * - /trending - Trending articles page
 * - /archive - Archive root page
 * - /about - About page
 * - /contact - Contact page
 * - /author/[slug] - Author profile pages
 *
 * Reserved for system use:
 * - /admin - Admin panel
 * - /login - Login page
 * - /api - API endpoints
 * - /sitemap - Sitemap.xml
 * - /robots - Robots.txt
 * - /feed - RSS feed
 * - /rss - RSS feed alternative
 * - /privacy - Privacy policy
 * - /terms - Terms of service
 * - /authors - Authors listing (alternative to /author)
 */

export const RESERVED_SLUGS = [
  'all',
  'search',
  'trending',
  'archive',
  'about',
  'contact',
  'author',
  'authors',
  'admin',
  'login',
  'api',
  'sitemap',
  'robots',
  'feed',
  'rss',
  'privacy',
  'terms',
] as const;

/**
 * Type for reserved slugs
 */
export type ReservedSlug = (typeof RESERVED_SLUGS)[number];

/**
 * Check if a slug is reserved
 */
export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.includes(slug as ReservedSlug);
}

/**
 * Get all reserved slugs
 */
export function getReservedSlugs(): readonly string[] {
  return RESERVED_SLUGS;
}

/**
 * Validate slug against reserved list
 * Returns error message if invalid, null if valid
 */
export function validateSlug(slug: string): string | null {
  if (isReservedSlug(slug)) {
    return `The slug "${slug}" is reserved for system pages and cannot be used.`;
  }
  return null;
}
