[deschide]
user = www-data
group = www-data
listen = /run/php/php-fpm-deschide.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 50
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20
pm.max_requests = 500
pm.process_idle_timeout = 10s

php_admin_value[error_log] = /var/log/php/deschide-fpm-error.log
php_admin_value[memory_limit] = 256M
php_admin_value[max_execution_time] = 30
php_admin_value[upload_max_filesize] = 15M
php_admin_value[post_max_size] = 20M
php_admin_value[expose_php] = Off

php_flag[display_errors] = Off
php_flag[log_errors] = On

env[APP_ENV] = prod
env[DATABASE_URL] = $DATABASE_URL
