/**
 * Reserved Slugs Generation Script
 *
 * Fetches reserved slugs from the backend API and generates the TypeScript constant file.
 * This ensures the frontend always has the latest reserved slugs from the backend.
 *
 * Usage:
 *   pnpm generate:slugs
 *   npm run generate:slugs
 *
 * Environment Variables:
 *   NEXT_PUBLIC_API_URL - Backend API URL (defaults to http://127.0.0.1:8081)
 */

import { writeFileSync } from 'fs';
import { join } from 'path';

interface ReservedSlugsResponse {
  success: boolean;
  reserved_slugs: string[];
  count: number;
}

/**
 * Fetch reserved slugs from backend API
 */
async function fetchReservedSlugs(): Promise<string[]> {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8081';
  const endpoint = `${apiUrl}/api/slug/reserved`;

  console.log(`📡 Fetching reserved slugs from: ${endpoint}`);

  try {
    const response = await fetch(endpoint, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(
        `Failed to fetch reserved slugs: ${response.status} ${response.statusText}`
      );
    }

    const data: ReservedSlugsResponse = await response.json();

    if (!data.success || !data.reserved_slugs || !Array.isArray(data.reserved_slugs)) {
      throw new Error('Invalid response format: expected { success: boolean, reserved_slugs: string[], count: number }');
    }

    console.log(`✅ Fetched ${data.count} reserved slugs from backend API`);
    return data.reserved_slugs;
  } catch (error) {
    console.error('❌ Error fetching reserved slugs from API:', error);
    console.log('⚠️  Falling back to default reserved slugs');

    // Fallback to default slugs if API is unavailable
    return [
      'all',
      'search',
      'trending',
      'archive',
      'about',
      'contact',
      'author',
      'authors',
      'admin',
      'login',
      'api',
      'sitemap',
      'robots',
      'feed',
      'rss',
      'privacy',
      'terms',
    ];
  }
}

/**
 * Generate TypeScript file content
 */
function generateTypeScriptFile(slugs: string[]): string {
  const timestamp = new Date().toISOString();
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8081';

  return `/**
 * Reserved Slugs
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from the backend API.
 * To regenerate, run: pnpm generate:slugs
 *
 * These slugs are reserved for system pages and cannot be used for categories.
 * This list is fetched from the backend validation in src/Validator/ReservedSlugValidator.php
 *
 * Generated: ${timestamp}
 * Source: ${apiUrl}/api/slug/reserved
 *
 * These routes have their own pages in app/[locale]/(public)/ directory:
 * - /all - All articles page
 * - /search - Search page
 * - /trending - Trending articles page
 * - /archive - Archive root page
 * - /about - About page
 * - /contact - Contact page
 * - /author/[slug] - Author profile pages
 *
 * Reserved for system use:
 * - /admin - Admin panel
 * - /login - Login page
 * - /api - API endpoints
 * - /sitemap - Sitemap.xml
 * - /robots - Robots.txt
 * - /feed - RSS feed
 * - /rss - RSS feed alternative
 * - /privacy - Privacy policy
 * - /terms - Terms of service
 * - /authors - Authors listing (alternative to /author)
 */

export const RESERVED_SLUGS = [
${slugs.map((slug) => `  '${slug}',`).join('\n')}
] as const;

/**
 * Type for reserved slugs
 */
export type ReservedSlug = (typeof RESERVED_SLUGS)[number];

/**
 * Check if a slug is reserved
 */
export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.includes(slug as ReservedSlug);
}

/**
 * Get all reserved slugs
 */
export function getReservedSlugs(): readonly string[] {
  return RESERVED_SLUGS;
}

/**
 * Validate slug against reserved list
 * Returns error message if invalid, null if valid
 */
export function validateSlug(slug: string): string | null {
  if (isReservedSlug(slug)) {
    return \`The slug "\${slug}" is reserved for system pages and cannot be used.\`;
  }
  return null;
}
`;
}

/**
 * Write generated content to file
 */
function writeGeneratedFile(content: string): void {
  const outputPath = join(
    process.cwd(),
    'lib',
    'constants',
    'reserved-slugs.ts'
  );

  console.log(`📝 Writing generated file to: ${outputPath}`);

  try {
    writeFileSync(outputPath, content, 'utf-8');
    console.log('✅ Successfully generated reserved-slugs.ts');
  } catch (error) {
    console.error('❌ Error writing file:', error);
    process.exit(1);
  }
}

/**
 * Validate generated slugs
 */
function validateSlugs(slugs: string[]): void {
  console.log('🔍 Validating generated slugs...');

  if (slugs.length === 0) {
    throw new Error('No slugs were generated');
  }

  if (slugs.length < 10) {
    console.warn(
      `⚠️  Warning: Only ${slugs.length} slugs generated. Expected at least 10.`
    );
  }

  // Check for duplicates
  const uniqueSlugs = new Set(slugs);
  if (uniqueSlugs.size !== slugs.length) {
    throw new Error('Duplicate slugs detected');
  }

  // Check for invalid characters
  const invalidSlugs = slugs.filter((slug) => !/^[a-z0-9-]+$/.test(slug));
  if (invalidSlugs.length > 0) {
    throw new Error(`Invalid slug format: ${invalidSlugs.join(', ')}`);
  }

  // Check for essential slugs
  const essentialSlugs = ['all', 'search', 'trending', 'archive', 'about', 'contact', 'author'];
  const missingSlugs = essentialSlugs.filter((slug) => !slugs.includes(slug));
  if (missingSlugs.length > 0) {
    console.warn(`⚠️  Warning: Missing essential slugs: ${missingSlugs.join(', ')}`);
  }

  console.log(`✅ Validation passed: ${slugs.length} valid slugs`);
}

/**
 * Display generation summary
 */
function displaySummary(slugs: string[]): void {
  console.log('\n📊 Generation Summary');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`Total slugs: ${slugs.length}`);
  console.log(`Output file: lib/constants/reserved-slugs.ts`);
  console.log('\nGenerated slugs:');
  slugs.forEach((slug, index) => {
    console.log(`  ${(index + 1).toString().padStart(2)}. ${slug}`);
  });
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
}

/**
 * Main execution
 */
async function main() {
  console.log('🚀 Starting reserved slugs generation...\n');

  try {
    // Fetch slugs from API
    const slugs = await fetchReservedSlugs();

    // Validate slugs
    validateSlugs(slugs);

    // Generate TypeScript file content
    const content = generateTypeScriptFile(slugs);

    // Write to file
    writeGeneratedFile(content);

    // Display summary
    displaySummary(slugs);

    console.log('✅ Reserved slugs generation completed successfully!\n');
    process.exit(0);
  } catch (error) {
    console.error('\n❌ Generation failed:', error);
    process.exit(1);
  }
}

// Execute
main();
