/**
 * Image type definitions aligned with deschide_backend Image entity
 */

export interface Image {
  '@id': string;
  '@type': string;
  id: number;
  file?: File | null;
  filename: string | null; // Unique filename generated by VichUploader
  originalFilename: string | null;
  mimeType: string | null;
  size: number | null;
  width: number | null;
  height: number | null;
  alt: string | null;
  caption: string | null;
  description: string | null;
  uploadedAt: string;
  updatedAt: string | null;
  aspectRatio: number | null;
  formattedSize: string | null;
}

export interface ImageListResponse {
  '@context': string;
  '@id': string;
  '@type': string;
  'hydra:member': Image[];
  'hydra:totalItems': number;
  'hydra:view'?: {
    '@id': string;
    '@type': string;
    'hydra:first'?: string;
    'hydra:last'?: string;
    'hydra:previous'?: string;
    'hydra:next'?: string;
  };
  'hydra:search'?: any;
}

/**
 * ArticleImage type definitions aligned with deschide_backend ArticleImage entity
 */

export interface ArticleImage {
  '@id': string;
  '@type': string;
  id: number;
  article: string; // IRI to Article
  image: Image | string; // Can be full Image object or IRI
  position: number;
  isFeatured: boolean;
}

export interface ArticleImageListResponse {
  '@context': string;
  '@id': string;
  '@type': string;
  'hydra:member': ArticleImage[];
  'hydra:totalItems': number;
  'hydra:view'?: {
    '@id': string;
    '@type': string;
    'hydra:first'?: string;
    'hydra:last'?: string;
    'hydra:previous'?: string;
    'hydra:next'?: string;
  };
}

/**
 * Client-side types for component state management
 */

export interface AttachedImage {
  id: number;
  articleImageId: number; // ID of the ArticleImage pivot record
  image: Image;
  position: number;
  isFeatured: boolean;
}

export interface ImageUploadProgress {
  filename: string;
  progress: number;
  status: 'uploading' | 'processing' | 'complete' | 'error';
  error?: string;
}

/**
 * Thumbnail and ThumbnailProfile types aligned with deschide_backend entities
 */

export interface CropCoordinates {
  x: number;      // X coordinate (px from left)
  y: number;      // Y coordinate (px from top)
  width: number;  // Width of crop box (px)
  height: number; // Height of crop box (px)
}

export interface ThumbnailProfile {
  '@id': string;
  '@type': string;
  id: number;
  name: string;                    // Unique identifier (e.g., "article_card")
  displayName: string;             // Human-readable name (translatable)
  description: string | null;      // Description (translatable)
  width: number;                   // Target width in pixels
  height: number;                  // Target height in pixels
  aspectRatio: string | null;      // User-defined aspect ratio (e.g., "16:9")
  calculatedAspectRatio: string;   // Computed from width/height (e.g., "1.778:1")
  dimensionsLabel: string;         // Computed label (e.g., "1920×1080")
  mode: string | null;             // Resize mode (e.g., "crop", "fit")
  quality: number;                 // JPEG quality (0-100)
  category: string | null;         // Category for grouping
  isActive: boolean;               // Whether profile is enabled
  createdAt: string;
  updatedAt: string | null;
  locale: string;
  translatableLocale: string | null;
}

export interface ThumbnailProfileListResponse {
  '@context': string;
  '@id': string;
  '@type': string;
  'hydra:member': ThumbnailProfile[];
  'hydra:totalItems': number;
  'hydra:view'?: {
    '@id': string;
    '@type': string;
    'hydra:first'?: string;
    'hydra:last'?: string;
    'hydra:previous'?: string;
    'hydra:next'?: string;
  };
}

export interface Thumbnail {
  '@id': string;
  '@type': string;
  id: number;
  filename: string;
  path: string;
  width: number;
  height: number;
  size: number;
  cropData: CropCoordinates | null;  // Custom crop coordinates (if applied)
  url: string;                        // Computed property - full URL
  formattedSize: string;              // Computed property - human-readable size
  aspectRatio: number;                // Computed property
  image: string;                      // IRI to parent Image
  profile: string | ThumbnailProfile; // IRI or full ThumbnailProfile object
  createdAt: string;
}

export interface ThumbnailListResponse {
  '@context': string;
  '@id': string;
  '@type': string;
  'hydra:member': Thumbnail[];
  'hydra:totalItems': number;
  'hydra:view'?: {
    '@id': string;
    '@type': string;
    'hydra:first'?: string;
    'hydra:last'?: string;
    'hydra:previous'?: string;
    'hydra:next'?: string;
  };
}

/**
 * Extended Image type with thumbnail data
 */
export interface ImageWithThumbnails extends Image {
  thumbnails: Thumbnail[];
}

/**
 * API request types for crop operations
 */
export interface ApplyCropRequest {
  profile: string;        // Profile name (e.g., "article_card")
  format: 'jpg' | 'webp'; // Output format
  cropData: CropCoordinates;
}

export interface ApplyCropResponse {
  success: boolean;
  message: string;
  thumbnail: Thumbnail;
}

/**
 * UI state types for crop modal
 */
export interface CropModalState {
  isOpen: boolean;
  image: ImageWithThumbnails | null;
  selectedProfile: ThumbnailProfile | null;
  selectedFormat: 'jpg' | 'webp';
  cropCoordinates: CropCoordinates | null;
}
