<?php

declare(strict_types=1);

namespace App\Factory;

use App\Entity\Article;
use App\Enum\ArticleStatus;
use Override;
use Zenstruck\Foundry\Persistence\PersistentObjectFactory;

/**
 * @extends PersistentObjectFactory<Article>
 */
final class ArticleFactory extends PersistentObjectFactory
{
    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#factories-as-services
     *
     * @todo inject services if required
     */
    public function __construct()
    {
    }

    #[Override]
    public static function class(): string
    {
        return Article::class;
    }

    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#model-factories
     *
     * @todo add your default values here
     */
    #[Override]
    protected function defaults(): array|callable
    {
        return [
            'title' => self::faker()->sentence(6, true),
            // slug is auto-generated by Gedmo
            'lead' => self::faker()->optional(0.8)->paragraph(),
            'content' => self::faker()->optional(0.9)->paragraphs(5, true),
            'status' => ArticleStatus::PUBLISHED,
            'publishedLocales' => ['ro'],
            'isFeatured' => self::faker()->boolean(20), // 20% chance of being featured
            'viewCount' => self::faker()->numberBetween(0, 10000),
            'category' => CategoryFactory::new(),
        ];
    }

    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#initialization
     */
    #[Override]
    protected function initialize(): static
    {
        return $this
            // ->afterInstantiate(function(Article $article): void {})
        ;
    }
}
