[program:mercure]
command=/usr/local/bin/mercure run --config /etc/mercure/Caddyfile
directory=/var/lib/mercure
user=radu
environment=MERCURE_PUBLISHER_JWT_KEY="HoSR2UHTYEufXrCGw94gOpIn76Es/aWE21zzXuK7NzexnoJ5eaJjRqy33h4TcSKC",MERCURE_SUBSCRIBER_JWT_KEY="HoSR2UHTYEufXrCGw94gOpIn76Es/aWE21zzXuK7NzexnoJ5eaJjRqy33h4TcSKC"
numprocs=1
autostart=true
autorestart=true
startsecs=3
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/deschide/mercure.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
