[program:messenger-translations]
command=/var/www/deschide_news_app/apps/backend/bin/console messenger:consume translations --limit=10 --time-limit=3600 -vv
directory=/var/www/deschide_news_app/apps/backend
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=5
startretries=10
redirect_stderr=false
stdout_logfile=/var/log/deschide/messenger-translations.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile=/var/log/deschide/messenger-translations.error.log
