[program:messenger-translations]
command=/usr/bin/symfony console messenger:consume translations_critical translations_urgent translations_high translations --limit=10 --time-limit=3600 -vv
directory=/var/www/deschide_news_app/apps/backend
user=radu
environment=HOME="/home/radu",PATH="/usr/local/bin:/usr/bin:/bin"
numprocs=1
autostart=false
autorestart=false
startsecs=5
startretries=10
stopwaitsecs=15
redirect_stderr=false
stdout_logfile=/var/log/deschide/messenger-translations.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile=/var/log/deschide/messenger-translations.error.log
stderr_logfile_maxbytes=10MB
