[program:messenger-python-scraper]
command=/usr/bin/symfony console messenger:consume python_scraper scheduler_python_scraper --limit=10 --time-limit=3600 -vv
directory=/var/www/deschide_news_app/apps/backend
user=radu
environment=HOME="/home/radu",PATH="/usr/local/bin:/usr/bin:/bin"
numprocs=1
autostart=true
autorestart=true
startsecs=5
startretries=10
stopwaitsecs=15
redirect_stderr=false
stdout_logfile=/var/log/deschide/messenger-python-scraper.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile=/var/log/deschide/messenger-python-scraper.error.log
stderr_logfile_maxbytes=10MB
