[program:messenger-topic-detection-staging]
command=/usr/bin/symfony console messenger:consume topic_detection --time-limit=3600 --memory-limit=256M --limit=100 -vv
directory=/var/www/deschide_news_app/apps/backend
user=radu
environment=APP_ENV=staging,HOME="/home/radu",PATH="/usr/local/bin:/usr/bin:/bin"
numprocs=1
autostart=false
autorestart=true
startsecs=5
startretries=10
stopwaitsecs=60
redirect_stderr=false
stdout_logfile=/var/log/deschide/staging/messenger-topic-detection-staging.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile=/var/log/deschide/staging/messenger-topic-detection-staging.error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
