<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * PressRelease↔Topic pivot table with detection metadata.
 *
 * Refs: T49.2, ADR-015
 */
final class Version20260416113144 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create press_release_topics pivot table with confidence, detectedBy, detectedAt';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE press_release_topics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, confidence DOUBLE PRECISION NOT NULL, detected_by VARCHAR(20) NOT NULL, detected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, press_release_id INT NOT NULL, topic_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A623E651F55203D ON press_release_topics (topic_id)');
        $this->addSql('CREATE INDEX idx_prt_topic_created ON press_release_topics (topic_id, detected_at)');
        $this->addSql('CREATE INDEX idx_prt_press_release ON press_release_topics (press_release_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_prt_pr_topic ON press_release_topics (press_release_id, topic_id)');
        $this->addSql('ALTER TABLE press_release_topics ADD CONSTRAINT FK_5A623E6578750292 FOREIGN KEY (press_release_id) REFERENCES press_releases (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE press_release_topics ADD CONSTRAINT FK_5A623E651F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE press_release_topics DROP CONSTRAINT FK_5A623E6578750292');
        $this->addSql('ALTER TABLE press_release_topics DROP CONSTRAINT FK_5A623E651F55203D');
        $this->addSql('DROP TABLE press_release_topics');
    }
}
