<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416135018 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create topic_briefings table for multi-cadence briefing infrastructure (ADR-016)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE topic_briefings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cadence VARCHAR(10) NOT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, title VARCHAR(255) DEFAULT NULL, summary_short TEXT DEFAULT NULL, summary_long TEXT DEFAULT NULL, key_facts JSON DEFAULT NULL, why_it_matters TEXT DEFAULT NULL, gemini_draft_raw TEXT DEFAULT NULL, claude_polished BOOLEAN DEFAULT false NOT NULL, pr_count INT DEFAULT 0 NOT NULL, period_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, period_to TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, topic_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_24CE29AE1F55203D ON topic_briefings (topic_id)');
        $this->addSql('CREATE INDEX idx_tb_topic_cadence ON topic_briefings (topic_id, cadence)');
        $this->addSql('CREATE INDEX idx_tb_cadence_status ON topic_briefings (cadence, status)');
        $this->addSql('CREATE INDEX idx_tb_created ON topic_briefings (created_at)');
        $this->addSql('CREATE INDEX idx_tb_period ON topic_briefings (period_from, period_to)');
        $this->addSql('ALTER TABLE topic_briefings ADD CONSTRAINT FK_24CE29AE1F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE topic_briefings DROP CONSTRAINT FK_24CE29AE1F55203D');
        $this->addSql('DROP TABLE topic_briefings');
    }
}
