<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328141727 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE press_releases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, lead TEXT DEFAULT NULL, content TEXT NOT NULL, source_email_id VARCHAR(64) NOT NULL, sender_address VARCHAR(255) NOT NULL, sender_name VARCHAR(255) NOT NULL, source_url VARCHAR(500) DEFAULT NULL, category_slug VARCHAR(50) NOT NULL, email_subject VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, content_length INT NOT NULL, processed_by_id INT DEFAULT NULL, article_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B6CA723EB12F71B ON press_releases (source_email_id)');
        $this->addSql('CREATE INDEX IDX_9B6CA7232FFD4FD3 ON press_releases (processed_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B6CA7237294869C ON press_releases (article_id)');
        $this->addSql('CREATE INDEX idx_press_release_status ON press_releases (status)');
        $this->addSql('CREATE INDEX idx_press_release_received ON press_releases (received_at)');
        $this->addSql('ALTER TABLE press_releases ADD CONSTRAINT FK_9B6CA7232FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE press_releases ADD CONSTRAINT FK_9B6CA7237294869C FOREIGN KEY (article_id) REFERENCES articles (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE press_releases DROP CONSTRAINT FK_9B6CA7232FFD4FD3');
        $this->addSql('ALTER TABLE press_releases DROP CONSTRAINT FK_9B6CA7237294869C');
        $this->addSql('DROP TABLE press_releases');
    }
}
