<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Sprint 56 T56.09 — DB-backed LLM invocation observability.
 *
 * Creates `llm_agent_call_log` so the S55 grep-based cost summary can be
 * retired. Promotes cost/duration/token telemetry from Monolog log files
 * (parsed by regex) to structured SQL aggregation in service of the T56.12
 * extended smoke readiness gate.
 *
 * Schema notes:
 *   - prompt_hash is SHA-256 hex (64 chars). Prompt TEXT is never stored —
 *     PII + size risk per ADR-022 D2 promotion.
 *   - invocation_id is a ULID string (26 chars).
 *   - model, verdict are nullable. model=null when the wrapper did not
 *     report it; verdict=null for non-gate agents (writers).
 *   - Token + cost columns default-zero at the PHP layer when the LLM
 *     wrapper does not expose them (e.g. Gemini CLI fallback path).
 */
final class Version20260420054809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'T56.09 — create llm_agent_call_log for DB-backed LLM cost/telemetry observability';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE llm_agent_call_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, agent_name VARCHAR(64) NOT NULL, invocation_id VARCHAR(26) NOT NULL, prompt_hash VARCHAR(64) NOT NULL, model VARCHAR(64) DEFAULT NULL, duration_ms INT NOT NULL, input_token_count INT NOT NULL, output_token_count INT NOT NULL, cache_read_token_count INT NOT NULL, cache_creation_token_count INT NOT NULL, cost_usd DOUBLE PRECISION NOT NULL, verdict VARCHAR(32) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_llm_call_agent_created ON llm_agent_call_log (agent_name, created_at)');
        $this->addSql('CREATE INDEX idx_llm_call_verdict ON llm_agent_call_log (verdict)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE llm_agent_call_log');
    }
}
