<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260330075511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create menu_items table for the Menu Builder system';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE menu_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, menu VARCHAR(20) NOT NULL, type VARCHAR(20) NOT NULL, label VARCHAR(255) NOT NULL, url VARCHAR(500) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, open_in_new_tab BOOLEAN DEFAULT false NOT NULL, css_class VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_menu_item_menu_active ON menu_items (menu, is_active, position)');
        $this->addSql('CREATE INDEX idx_menu_item_category ON menu_items (category_id)');
        $this->addSql('COMMENT ON COLUMN menu_items.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN menu_items.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE menu_items DROP CONSTRAINT FK_70B2CA2A12469DE2');
        $this->addSql('DROP TABLE menu_items');
    }
}
