<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260415141549 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create curation_suggestions table for ClusterCuratorService.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE curation_suggestions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, cluster_ids JSON NOT NULL, target_cluster_id INT DEFAULT NULL, reason TEXT NOT NULL, suggested_topic VARCHAR(100) DEFAULT NULL, confidence DOUBLE PRECISION NOT NULL, suggested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resolved_by VARCHAR(100) DEFAULT NULL, cluster_headlines JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_curation_status ON curation_suggestions (status)');
        $this->addSql('CREATE INDEX idx_curation_type ON curation_suggestions (type)');
        $this->addSql("COMMENT ON COLUMN curation_suggestions.suggested_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN curation_suggestions.resolved_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE curation_suggestions');
    }
}
