<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404081314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create topics table (Nested Set tree) and article_topics join table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE topics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, lft INT NOT NULL, rgt INT NOT NULL, lvl INT NOT NULL, position INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id INT DEFAULT NULL, root_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_91F64639989D9B62 ON topics (slug)');
        $this->addSql('CREATE INDEX idx_topic_slug ON topics (slug)');
        $this->addSql('CREATE INDEX idx_topic_is_active ON topics (is_active)');
        $this->addSql('CREATE INDEX idx_topic_lft_rgt ON topics (lft, rgt)');
        $this->addSql('CREATE INDEX idx_topic_parent ON topics (parent_id)');
        $this->addSql('CREATE INDEX idx_topic_root ON topics (root_id)');
        $this->addSql('CREATE TABLE article_topics (topic_id INT NOT NULL, article_id INT NOT NULL, PRIMARY KEY (topic_id, article_id))');
        $this->addSql('CREATE INDEX IDX_FB31D1B91F55203D ON article_topics (topic_id)');
        $this->addSql('CREATE INDEX IDX_FB31D1B97294869C ON article_topics (article_id)');
        $this->addSql('ALTER TABLE topics ADD CONSTRAINT FK_91F64639727ACA70 FOREIGN KEY (parent_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topics ADD CONSTRAINT FK_91F6463979066886 FOREIGN KEY (root_id) REFERENCES topics (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE article_topics ADD CONSTRAINT FK_FB31D1B91F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_topics ADD CONSTRAINT FK_FB31D1B97294869C FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE topics DROP CONSTRAINT FK_91F64639727ACA70');
        $this->addSql('ALTER TABLE topics DROP CONSTRAINT FK_91F6463979066886');
        $this->addSql('ALTER TABLE article_topics DROP CONSTRAINT FK_FB31D1B91F55203D');
        $this->addSql('ALTER TABLE article_topics DROP CONSTRAINT FK_FB31D1B97294869C');
        $this->addSql('DROP TABLE topics');
        $this->addSql('DROP TABLE article_topics');
    }
}
