<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260406050607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add relevance_keywords table for DB-driven keyword management';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE relevance_keywords (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, keyword VARCHAR(100) NOT NULL, tier SMALLINT NOT NULL, language VARCHAR(5) NOT NULL, is_active BOOLEAN NOT NULL, added_by VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rk_tier ON relevance_keywords (tier)');
        $this->addSql('CREATE INDEX idx_rk_is_active ON relevance_keywords (is_active)');
        $this->addSql('CREATE INDEX idx_rk_language ON relevance_keywords (language)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE relevance_keywords');
    }
}
