<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260413083444 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add AI generation metadata fields to articles (aiGenerated, sourceClusterId, aiConfidenceScore, aiSourceCount). Drop orphaned cluster_background_proposals table.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE IF EXISTS cluster_background_proposals');
        $this->addSql('ALTER TABLE articles ADD ai_generated BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE articles ADD source_cluster_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE articles ADD ai_confidence_score DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE articles ADD ai_source_count INT DEFAULT NULL');
        $this->addSql('ALTER TABLE articles DROP COLUMN IF EXISTS background');
        $this->addSql('ALTER TABLE story_clusters DROP COLUMN IF EXISTS background_generated');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cluster_background_proposals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, blocks JSON NOT NULL, quality_score DOUBLE PRECISION NOT NULL, context_sufficiency VARCHAR(20) NOT NULL, total_sources_found INT NOT NULL, issues JSON NOT NULL, model_used VARCHAR(50) NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, story_cluster_id INT NOT NULL, article_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cbp_status ON cluster_background_proposals (status)');
        $this->addSql('CREATE INDEX idx_cbp_article ON cluster_background_proposals (article_id)');
        $this->addSql('CREATE INDEX idx_cbp_cluster ON cluster_background_proposals (story_cluster_id)');
        $this->addSql('ALTER TABLE cluster_background_proposals ADD CONSTRAINT fk_e57ffc4de491c8b8 FOREIGN KEY (story_cluster_id) REFERENCES story_clusters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cluster_background_proposals ADD CONSTRAINT fk_e57ffc4d7294869c FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articles ADD background TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE articles DROP ai_generated');
        $this->addSql('ALTER TABLE articles DROP source_cluster_id');
        $this->addSql('ALTER TABLE articles DROP ai_confidence_score');
        $this->addSql('ALTER TABLE articles DROP ai_source_count');
        $this->addSql('ALTER TABLE story_clusters ADD background_generated BOOLEAN DEFAULT false NOT NULL');
    }
}
