<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260418085622 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'T53.2 (Sprint 53, ADR-020 D4) — create source_signals table with composite unique (verified_source_id, raw_content_hash)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE source_signals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, captured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_url TEXT NOT NULL, canonical_url TEXT DEFAULT NULL, title TEXT NOT NULL, raw_summary TEXT DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source_attribution TEXT DEFAULT NULL, source_links_out JSON DEFAULT NULL, raw_content_hash VARCHAR(64) NOT NULL, raw_payload JSON DEFAULT NULL, verified_source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9F727D65DD61A775 ON source_signals (verified_source_id)');
        $this->addSql('CREATE INDEX idx_source_signals_source_captured ON source_signals (verified_source_id, captured_at)');
        $this->addSql('CREATE INDEX idx_source_signals_captured_at ON source_signals (captured_at)');
        $this->addSql('CREATE INDEX idx_source_signals_published_at ON source_signals (published_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_source_signal_source_hash ON source_signals (verified_source_id, raw_content_hash)');
        $this->addSql('ALTER TABLE source_signals ADD CONSTRAINT FK_9F727D65DD61A775 FOREIGN KEY (verified_source_id) REFERENCES verified_sources (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE source_signals DROP CONSTRAINT FK_9F727D65DD61A775');
        $this->addSql('DROP TABLE source_signals');
    }
}
