<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260418090026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'T53.3 (Sprint 53, ADR-020 D4) — create editorial_escalation_log + source_claim_history schema-only tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE editorial_escalation_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, article_snapshot JSON NOT NULL, category_code VARCHAR(40) NOT NULL, origin_graph_snapshot JSON NOT NULL, decision VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, decided_by_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_editorial_escalation_log_created_at ON editorial_escalation_log (created_at)');
        $this->addSql('CREATE INDEX idx_editorial_escalation_log_decision ON editorial_escalation_log (decision)');
        $this->addSql('CREATE INDEX idx_editorial_escalation_log_category ON editorial_escalation_log (category_code)');
        $this->addSql('CREATE INDEX idx_editorial_escalation_log_decided_by ON editorial_escalation_log (decided_by_user_id)');
        $this->addSql('CREATE TABLE source_claim_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, claim_text TEXT NOT NULL, outcome VARCHAR(20) NOT NULL, observed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, verified_source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_source_claim_history_source ON source_claim_history (verified_source_id)');
        $this->addSql('CREATE INDEX idx_source_claim_history_observed_at ON source_claim_history (observed_at)');
        $this->addSql('CREATE INDEX idx_source_claim_history_outcome ON source_claim_history (outcome)');
        $this->addSql('ALTER TABLE editorial_escalation_log ADD CONSTRAINT FK_F99C2536515F5BC8 FOREIGN KEY (decided_by_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE source_claim_history ADD CONSTRAINT FK_732D4E17DD61A775 FOREIGN KEY (verified_source_id) REFERENCES verified_sources (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE editorial_escalation_log DROP CONSTRAINT FK_F99C2536515F5BC8');
        $this->addSql('ALTER TABLE source_claim_history DROP CONSTRAINT FK_732D4E17DD61A775');
        $this->addSql('DROP TABLE editorial_escalation_log');
        $this->addSql('DROP TABLE source_claim_history');
    }
}
