<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407111605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Sprint 30: Add StoryCluster and Source entities, extend PressRelease and Topic';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, rss_url VARCHAR(2048) DEFAULT NULL, credibility_weight DOUBLE PRECISION DEFAULT 0.5 NOT NULL, country VARCHAR(2) DEFAULT NULL, source_category VARCHAR(30) DEFAULT NULL, fetch_frequency_minutes INT DEFAULT 60 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, type VARCHAR(20) DEFAULT \'rss\' NOT NULL, domain_pattern VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D25D65F25E237E06 ON sources (name)');
        $this->addSql('CREATE INDEX idx_source_is_active ON sources (is_active)');
        $this->addSql('CREATE INDEX idx_source_country ON sources (country)');
        $this->addSql('CREATE INDEX idx_source_category ON sources (source_category)');
        $this->addSql('CREATE TABLE story_clusters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, primary_headline VARCHAR(500) NOT NULL, summary_short TEXT DEFAULT NULL, summary_medium TEXT DEFAULT NULL, why_it_matters TEXT DEFAULT NULL, key_facts JSON DEFAULT NULL, importance_score DOUBLE PRECISION DEFAULT 0 NOT NULL, source_count INT DEFAULT 0 NOT NULL, article_count INT DEFAULT 0 NOT NULL, region_tags JSON DEFAULT NULL, status VARCHAR(20) DEFAULT \'auto\' NOT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, promoted_to_press_release BOOLEAN DEFAULT false NOT NULL, editorial_boost DOUBLE PRECISION DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cluster_importance ON story_clusters (importance_score)');
        $this->addSql('CREATE INDEX idx_cluster_status ON story_clusters (status)');
        $this->addSql('CREATE INDEX idx_cluster_first_seen ON story_clusters (first_seen_at)');
        $this->addSql('CREATE INDEX idx_cluster_promoted ON story_clusters (promoted_to_press_release)');
        $this->addSql('CREATE TABLE story_cluster_press_release (story_cluster_id INT NOT NULL, press_release_id INT NOT NULL, PRIMARY KEY (story_cluster_id, press_release_id))');
        $this->addSql('CREATE INDEX IDX_959A3F4FE491C8B8 ON story_cluster_press_release (story_cluster_id)');
        $this->addSql('CREATE INDEX IDX_959A3F4F78750292 ON story_cluster_press_release (press_release_id)');
        $this->addSql('CREATE TABLE story_cluster_topic (story_cluster_id INT NOT NULL, topic_id INT NOT NULL, PRIMARY KEY (story_cluster_id, topic_id))');
        $this->addSql('CREATE INDEX IDX_CB23D4A4E491C8B8 ON story_cluster_topic (story_cluster_id)');
        $this->addSql('CREATE INDEX IDX_CB23D4A41F55203D ON story_cluster_topic (topic_id)');
        $this->addSql('ALTER TABLE story_cluster_press_release ADD CONSTRAINT FK_959A3F4FE491C8B8 FOREIGN KEY (story_cluster_id) REFERENCES story_clusters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE story_cluster_press_release ADD CONSTRAINT FK_959A3F4F78750292 FOREIGN KEY (press_release_id) REFERENCES press_releases (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE story_cluster_topic ADD CONSTRAINT FK_CB23D4A4E491C8B8 FOREIGN KEY (story_cluster_id) REFERENCES story_clusters (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE story_cluster_topic ADD CONSTRAINT FK_CB23D4A41F55203D FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE press_releases ADD detected_language VARCHAR(5) DEFAULT NULL');
        $this->addSql('ALTER TABLE topics ADD weight DOUBLE PRECISION DEFAULT 0.5 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE story_cluster_press_release DROP CONSTRAINT FK_959A3F4FE491C8B8');
        $this->addSql('ALTER TABLE story_cluster_press_release DROP CONSTRAINT FK_959A3F4F78750292');
        $this->addSql('ALTER TABLE story_cluster_topic DROP CONSTRAINT FK_CB23D4A4E491C8B8');
        $this->addSql('ALTER TABLE story_cluster_topic DROP CONSTRAINT FK_CB23D4A41F55203D');
        $this->addSql('DROP TABLE sources');
        $this->addSql('DROP TABLE story_clusters');
        $this->addSql('DROP TABLE story_cluster_press_release');
        $this->addSql('DROP TABLE story_cluster_topic');
        $this->addSql('ALTER TABLE press_releases DROP detected_language');
        $this->addSql('ALTER TABLE topics DROP weight');
    }
}
