<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260418084958 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'T53.1 (Sprint 53, ADR-020 D4) — create verified_sources table with FK to sources(id) ON DELETE SET NULL';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE verified_sources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, tier SMALLINT NOT NULL, editorial_alignment VARCHAR(40) NOT NULL, trust_score_baseline NUMERIC(3, 2) NOT NULL, trust_score_rolling NUMERIC(3, 2) DEFAULT NULL, enabled BOOLEAN DEFAULT true NOT NULL, editorial_notes TEXT DEFAULT NULL, language VARCHAR(2) DEFAULT NULL, url VARCHAR(2048) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8A12E8B1989D9B62 ON verified_sources (slug)');
        $this->addSql('CREATE INDEX IDX_8A12E8B1953C1C61 ON verified_sources (source_id)');
        $this->addSql('CREATE INDEX idx_verified_sources_alignment ON verified_sources (editorial_alignment)');
        $this->addSql('CREATE INDEX idx_verified_sources_tier ON verified_sources (tier)');
        $this->addSql('CREATE INDEX idx_verified_sources_enabled ON verified_sources (enabled)');
        $this->addSql('ALTER TABLE verified_sources ADD CONSTRAINT FK_8A12E8B1953C1C61 FOREIGN KEY (source_id) REFERENCES sources (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE verified_sources DROP CONSTRAINT FK_8A12E8B1953C1C61');
        $this->addSql('DROP TABLE verified_sources');
    }
}
