<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422072903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'T57.P3 (Sprint 57, ADR-024 D5) — create app_settings_audit_log for AppSetting update auditing';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_settings_audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(100) NOT NULL, old_value TEXT DEFAULT NULL, new_value TEXT NOT NULL, changed_by VARCHAR(100) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reason TEXT DEFAULT NULL, context JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_app_settings_audit_key_changed_at ON app_settings_audit_log (setting_key, changed_at)');
        $this->addSql('CREATE INDEX idx_app_settings_audit_changed_at ON app_settings_audit_log (changed_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE app_settings_audit_log');
    }
}
